/*
  Subastas Copart - SQL Server 2019 o posterior.
  Ejecutar en la base de datos elegida, desde SSMS o Azure Data Studio.
  Todos los nombres de tablas terminan en 2105.
  Fecha/hora persistida en UTC; Q es la moneda funcional de la aplicacion.
  El script crea objetos nuevos; no es una migracion idempotente.
*/

CREATE TABLE dbo.USUARIOS2105 (
    USUARIO_ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_USUARIOS2105 PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    APELLIDO NVARCHAR(100) NOT NULL,
    CORREO NVARCHAR(320) NOT NULL,
    TELEFONO NVARCHAR(30) NOT NULL,
    CONTRASENA_HASH NVARCHAR(255) NOT NULL,
    ROL VARCHAR(20) NOT NULL CONSTRAINT DF_USUARIOS2105_ROL DEFAULT ('USUARIO'),
    ACTIVO BIT NOT NULL CONSTRAINT DF_USUARIOS2105_ACTIVO DEFAULT (1),
    CREADO_UTC DATETIME2(3) NOT NULL CONSTRAINT DF_USUARIOS2105_CREADO DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT UQ_USUARIOS2105_CORREO UNIQUE (CORREO),
    CONSTRAINT CK_USUARIOS2105_ROL CHECK (ROL IN ('USUARIO', 'ADMIN')),
    CONSTRAINT CK_USUARIOS2105_NOMBRE CHECK (LEN(LTRIM(RTRIM(NOMBRE))) > 0),
    CONSTRAINT CK_USUARIOS2105_APELLIDO CHECK (LEN(LTRIM(RTRIM(APELLIDO))) > 0)
);

CREATE TABLE dbo.TIPOS_ARTICULO2105 (
    TIPO_ARTICULO_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TIPOS_ARTICULO2105 PRIMARY KEY,
    NOMBRE NVARCHAR(80) NOT NULL CONSTRAINT UQ_TIPOS_ARTICULO2105_NOMBRE UNIQUE
);

CREATE TABLE dbo.MARCAS2105 (
    MARCA_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_MARCAS2105 PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL CONSTRAINT UQ_MARCAS2105_NOMBRE UNIQUE
);

CREATE TABLE dbo.MODELOS2105 (
    MODELO_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_MODELOS2105 PRIMARY KEY,
    MARCA_ID INT NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    CONSTRAINT FK_MODELOS2105_MARCAS FOREIGN KEY (MARCA_ID) REFERENCES dbo.MARCAS2105 (MARCA_ID),
    CONSTRAINT UQ_MODELOS2105_MARCA_NOMBRE UNIQUE (MARCA_ID, NOMBRE),
    CONSTRAINT UQ_MODELOS2105_MARCA_ID UNIQUE (MARCA_ID, MODELO_ID)
);

CREATE TABLE dbo.TRANSMISIONES2105 (
    TRANSMISION_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TRANSMISIONES2105 PRIMARY KEY,
    NOMBRE NVARCHAR(80) NOT NULL CONSTRAINT UQ_TRANSMISIONES2105_NOMBRE UNIQUE
);

CREATE TABLE dbo.COMBUSTIBLES2105 (
    COMBUSTIBLE_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_COMBUSTIBLES2105 PRIMARY KEY,
    NOMBRE NVARCHAR(80) NOT NULL CONSTRAINT UQ_COMBUSTIBLES2105_NOMBRE UNIQUE
);

CREATE TABLE dbo.TRACCIONES2105 (
    TRACCION_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TRACCIONES2105 PRIMARY KEY,
    CODIGO VARCHAR(4) NOT NULL CONSTRAINT UQ_TRACCIONES2105_CODIGO UNIQUE,
    CONSTRAINT CK_TRACCIONES2105_CODIGO CHECK (CODIGO IN ('AWD', 'FWD', 'RWD', '4WD'))
);

CREATE TABLE dbo.NIVELES_DANO2105 (
    NIVEL_DANO_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_NIVELES_DANO2105 PRIMARY KEY,
    CODIGO VARCHAR(10) NOT NULL CONSTRAINT UQ_NIVELES_DANO2105_CODIGO UNIQUE,
    DESCRIPCION NVARCHAR(100) NOT NULL,
    CONSTRAINT CK_NIVELES_DANO2105_CODIGO CHECK (CODIGO IN ('VERDE', 'AMARILLO', 'ROJO'))
);

CREATE TABLE dbo.VEHICULOS2105 (
    VEHICULO_ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_VEHICULOS2105 PRIMARY KEY,
    PUBLICADOR_USUARIO_ID BIGINT NOT NULL,
    ANIO SMALLINT NOT NULL,
    TIPO_ARTICULO_ID INT NOT NULL,
    MARCA_ID INT NOT NULL,
    MODELO_ID INT NOT NULL,
    MOTOR NVARCHAR(100) NOT NULL,
    TRANSMISION_ID INT NOT NULL,
    COMBUSTIBLE_ID INT NOT NULL,
    TRACCION_ID INT NOT NULL,
    NUMERO_CILINDROS TINYINT NOT NULL,
    NIVEL_DANO_ID INT NOT NULL,
    CREADO_UTC DATETIME2(3) NOT NULL CONSTRAINT DF_VEHICULOS2105_CREADO DEFAULT (SYSUTCDATETIME()),
    ACTUALIZADO_UTC DATETIME2(3) NULL,
    VERSION_FILA ROWVERSION NOT NULL,
    CONSTRAINT FK_VEHICULOS2105_PUBLICADOR FOREIGN KEY (PUBLICADOR_USUARIO_ID) REFERENCES dbo.USUARIOS2105 (USUARIO_ID),
    CONSTRAINT FK_VEHICULOS2105_TIPO FOREIGN KEY (TIPO_ARTICULO_ID) REFERENCES dbo.TIPOS_ARTICULO2105 (TIPO_ARTICULO_ID),
    CONSTRAINT FK_VEHICULOS2105_MARCA_MODELO FOREIGN KEY (MARCA_ID, MODELO_ID) REFERENCES dbo.MODELOS2105 (MARCA_ID, MODELO_ID),
    CONSTRAINT FK_VEHICULOS2105_TRANSMISION FOREIGN KEY (TRANSMISION_ID) REFERENCES dbo.TRANSMISIONES2105 (TRANSMISION_ID),
    CONSTRAINT FK_VEHICULOS2105_COMBUSTIBLE FOREIGN KEY (COMBUSTIBLE_ID) REFERENCES dbo.COMBUSTIBLES2105 (COMBUSTIBLE_ID),
    CONSTRAINT FK_VEHICULOS2105_TRACCION FOREIGN KEY (TRACCION_ID) REFERENCES dbo.TRACCIONES2105 (TRACCION_ID),
    CONSTRAINT FK_VEHICULOS2105_DANO FOREIGN KEY (NIVEL_DANO_ID) REFERENCES dbo.NIVELES_DANO2105 (NIVEL_DANO_ID),
    CONSTRAINT CK_VEHICULOS2105_ANIO CHECK (ANIO BETWEEN 1886 AND 9999),
    CONSTRAINT CK_VEHICULOS2105_MOTOR CHECK (LEN(LTRIM(RTRIM(MOTOR))) > 0),
    CONSTRAINT CK_VEHICULOS2105_CILINDROS CHECK (NUMERO_CILINDROS <= 24)
);

CREATE TABLE dbo.FOTOS_VEHICULO2105 (
    FOTO_ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_FOTOS_VEHICULO2105 PRIMARY KEY,
    VEHICULO_ID BIGINT NOT NULL,
    NOMBRE_ARCHIVO NVARCHAR(255) NOT NULL,
    TIPO_MIME VARCHAR(20) NOT NULL,
    IMAGEN VARBINARY(MAX) NOT NULL,
    ORDEN INT NOT NULL,
    CREADO_UTC DATETIME2(3) NOT NULL CONSTRAINT DF_FOTOS_VEHICULO2105_CREADO DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT FK_FOTOS_VEHICULO2105_VEHICULO FOREIGN KEY (VEHICULO_ID) REFERENCES dbo.VEHICULOS2105 (VEHICULO_ID),
    CONSTRAINT UQ_FOTOS_VEHICULO2105_ORDEN UNIQUE (VEHICULO_ID, ORDEN),
    CONSTRAINT CK_FOTOS_VEHICULO2105_ORDEN CHECK (ORDEN > 0),
    CONSTRAINT CK_FOTOS_VEHICULO2105_NOMBRE CHECK (LEN(LTRIM(RTRIM(NOMBRE_ARCHIVO))) > 0),
    CONSTRAINT CK_FOTOS_VEHICULO2105_MIME CHECK (TIPO_MIME IN ('image/jpeg', 'image/png', 'image/webp')),
    CONSTRAINT CK_FOTOS_VEHICULO2105_IMAGEN CHECK (DATALENGTH(IMAGEN) > 0)
);

CREATE TABLE dbo.SUBASTAS2105 (
    SUBASTA_ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_SUBASTAS2105 PRIMARY KEY,
    VEHICULO_ID BIGINT NOT NULL CONSTRAINT UQ_SUBASTAS2105_VEHICULO UNIQUE,
    PRECIO_BASE DECIMAL(19,2) NOT NULL,
    INICIO_UTC DATETIME2(3) NOT NULL,
    FIN_UTC DATETIME2(3) NOT NULL,
    ESTADO VARCHAR(12) NOT NULL CONSTRAINT DF_SUBASTAS2105_ESTADO DEFAULT ('BORRADOR'),
    RESULTADO VARCHAR(8) NULL,
    CERRADA_UTC DATETIME2(3) NULL,
    CREADO_UTC DATETIME2(3) NOT NULL CONSTRAINT DF_SUBASTAS2105_CREADO DEFAULT (SYSUTCDATETIME()),
    VERSION_FILA ROWVERSION NOT NULL,
    CONSTRAINT FK_SUBASTAS2105_VEHICULO FOREIGN KEY (VEHICULO_ID) REFERENCES dbo.VEHICULOS2105 (VEHICULO_ID),
    CONSTRAINT CK_SUBASTAS2105_PRECIO CHECK (PRECIO_BASE > 0),
    CONSTRAINT CK_SUBASTAS2105_FECHAS CHECK (INICIO_UTC < FIN_UTC),
    CONSTRAINT CK_SUBASTAS2105_ESTADO CHECK (ESTADO IN ('BORRADOR', 'PUBLICADA', 'CERRADA', 'CANCELADA')),
    CONSTRAINT CK_SUBASTAS2105_RESULTADO CHECK
      ((ESTADO = 'CERRADA' AND RESULTADO IS NOT NULL AND RESULTADO IN ('VENDIDA', 'DESIERTA') AND CERRADA_UTC IS NOT NULL)
        OR (ESTADO <> 'CERRADA' AND RESULTADO IS NULL AND CERRADA_UTC IS NULL))
);

CREATE TABLE dbo.PUJAS2105 (
    PUJA_ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PUJAS2105 PRIMARY KEY,
    SUBASTA_ID BIGINT NOT NULL,
    USUARIO_ID BIGINT NOT NULL,
    MONTO DECIMAL(19,2) NOT NULL,
    CREADO_UTC DATETIME2(3) NOT NULL CONSTRAINT DF_PUJAS2105_CREADO DEFAULT (SYSUTCDATETIME()),
    CONSTRAINT FK_PUJAS2105_SUBASTA FOREIGN KEY (SUBASTA_ID) REFERENCES dbo.SUBASTAS2105 (SUBASTA_ID),
    CONSTRAINT FK_PUJAS2105_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES dbo.USUARIOS2105 (USUARIO_ID),
    CONSTRAINT CK_PUJAS2105_MONTO CHECK (MONTO > 0)
);

CREATE TABLE dbo.NOTIFICACIONES2105 (
    NOTIFICACION_ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_NOTIFICACIONES2105 PRIMARY KEY,
    USUARIO_ID BIGINT NOT NULL,
    SUBASTA_ID BIGINT NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    CREADO_UTC DATETIME2(3) NOT NULL CONSTRAINT DF_NOTIFICACIONES2105_CREADO DEFAULT (SYSUTCDATETIME()),
    LEIDO_UTC DATETIME2(3) NULL,
    CONSTRAINT FK_NOTIFICACIONES2105_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES dbo.USUARIOS2105 (USUARIO_ID),
    CONSTRAINT FK_NOTIFICACIONES2105_SUBASTA FOREIGN KEY (SUBASTA_ID) REFERENCES dbo.SUBASTAS2105 (SUBASTA_ID),
    CONSTRAINT CK_NOTIFICACIONES2105_TIPO CHECK
        (TIPO IN ('GANANDO', 'SUPERADO', 'VENDIDA', 'DESIERTA'))
);

-- Bandeja de eventos: el servidor web emite WebSocket/SignalR tras confirmar la transaccion.
CREATE TABLE dbo.EVENTOS_SUBASTA2105 (
    EVENTO_ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_EVENTOS_SUBASTA2105 PRIMARY KEY,
    SUBASTA_ID BIGINT NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    MONTO_PUBLICO DECIMAL(19,2) NULL,
    CREADO_UTC DATETIME2(3) NOT NULL CONSTRAINT DF_EVENTOS_SUBASTA2105_CREADO DEFAULT (SYSUTCDATETIME()),
    PROCESADO_UTC DATETIME2(3) NULL,
    INTENTOS INT NOT NULL CONSTRAINT DF_EVENTOS_SUBASTA2105_INTENTOS DEFAULT (0),
    CONSTRAINT FK_EVENTOS_SUBASTA2105_SUBASTA FOREIGN KEY (SUBASTA_ID) REFERENCES dbo.SUBASTAS2105 (SUBASTA_ID),
    CONSTRAINT CK_EVENTOS_SUBASTA2105_TIPO CHECK
        (TIPO IN ('PUBLICADA', 'PUJA', 'CERRADA')),
    CONSTRAINT CK_EVENTOS_SUBASTA2105_MONTO CHECK (MONTO_PUBLICO IS NULL OR MONTO_PUBLICO > 0),
    CONSTRAINT CK_EVENTOS_SUBASTA2105_INTENTOS CHECK (INTENTOS >= 0)
);
GO

CREATE INDEX IX_VEHICULOS2105_PUBLICADOR ON dbo.VEHICULOS2105 (PUBLICADOR_USUARIO_ID, CREADO_UTC DESC);
CREATE INDEX IX_VEHICULOS2105_FILTROS ON dbo.VEHICULOS2105
    (MARCA_ID, MODELO_ID, NIVEL_DANO_ID, COMBUSTIBLE_ID, ANIO);
CREATE INDEX IX_SUBASTAS2105_CIERRE ON dbo.SUBASTAS2105 (ESTADO, FIN_UTC);
CREATE UNIQUE INDEX UX_PUJAS2105_SUBASTA_MONTO ON dbo.PUJAS2105 (SUBASTA_ID, MONTO DESC);
CREATE INDEX IX_PUJAS2105_USUARIO ON dbo.PUJAS2105 (USUARIO_ID, CREADO_UTC DESC);
CREATE INDEX IX_NOTIFICACIONES2105_USUARIO ON dbo.NOTIFICACIONES2105 (USUARIO_ID, CREADO_UTC DESC);
CREATE INDEX IX_EVENTOS_SUBASTA2105_PENDIENTES ON dbo.EVENTOS_SUBASTA2105 (EVENTO_ID)
    WHERE PROCESADO_UTC IS NULL;
GO

INSERT INTO dbo.TRACCIONES2105 (CODIGO) VALUES ('AWD'), ('FWD'), ('RWD'), ('4WD');
INSERT INTO dbo.NIVELES_DANO2105 (CODIGO, DESCRIPCION) VALUES
  ('VERDE', N'Daño menor / Limpio'),
  ('AMARILLO', N'Daño medio / Reparable'),
  ('ROJO', N'Daño severo / Salvamento');
GO

CREATE OR ALTER PROCEDURE dbo.PUBLICAR_SUBASTA2105
    @SUBASTA_ID BIGINT,
    @PUBLICADOR_USUARIO_ID BIGINT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @DUENO BIGINT, @ESTADO VARCHAR(12), @FIN DATETIME2(3);

    BEGIN TRY
        BEGIN TRANSACTION;
        SELECT @DUENO = v.PUBLICADOR_USUARIO_ID, @ESTADO = s.ESTADO, @FIN = s.FIN_UTC
        FROM dbo.SUBASTAS2105 AS s WITH (UPDLOCK, HOLDLOCK)
        JOIN dbo.VEHICULOS2105 AS v ON v.VEHICULO_ID = s.VEHICULO_ID
        WHERE s.SUBASTA_ID = @SUBASTA_ID;

        IF @DUENO IS NULL THROW 51000, 'La subasta no existe.', 1;
        IF @DUENO <> @PUBLICADOR_USUARIO_ID THROW 51001, 'No es el publicador.', 1;
        IF NOT EXISTS (SELECT 1 FROM dbo.USUARIOS2105 WHERE USUARIO_ID = @DUENO AND ACTIVO = 1)
            THROW 51002, 'El publicador no esta activo.', 1;
        IF @ESTADO <> 'BORRADOR' THROW 51003, 'La subasta no esta en borrador.', 1;
        IF @FIN <= SYSUTCDATETIME() THROW 51004, 'La fecha de cierre ya paso.', 1;
        IF (SELECT COUNT_BIG(*) FROM dbo.FOTOS_VEHICULO2105 WHERE VEHICULO_ID =
            (SELECT VEHICULO_ID FROM dbo.SUBASTAS2105 WHERE SUBASTA_ID = @SUBASTA_ID)) < 5
            THROW 51005, 'Se requieren al menos cinco fotografias.', 1;

        UPDATE dbo.SUBASTAS2105 SET ESTADO = 'PUBLICADA' WHERE SUBASTA_ID = @SUBASTA_ID;
        INSERT dbo.EVENTOS_SUBASTA2105 (SUBASTA_ID, TIPO) VALUES (@SUBASTA_ID, 'PUBLICADA');
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

CREATE OR ALTER PROCEDURE dbo.REGISTRAR_PUJA2105
    @SUBASTA_ID BIGINT,
    @USUARIO_ID BIGINT, -- El servidor obtiene este ID de la sesion autenticada.
    @MONTO DECIMAL(19,2)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @ESTADO VARCHAR(12), @BASE DECIMAL(19,2),
            @INICIO DATETIME2(3), @FIN DATETIME2(3), @AHORA DATETIME2(3),
            @ANTERIOR_MONTO DECIMAL(19,2), @ANTERIOR_USUARIO_ID BIGINT,
            @PUJA_ID BIGINT;

    BEGIN TRY
        BEGIN TRANSACTION;
        SELECT @ESTADO = ESTADO, @BASE = PRECIO_BASE,
               @INICIO = INICIO_UTC, @FIN = FIN_UTC
        FROM dbo.SUBASTAS2105 WITH (UPDLOCK, HOLDLOCK)
        WHERE SUBASTA_ID = @SUBASTA_ID;

        IF @ESTADO IS NULL THROW 51100, 'La subasta no existe.', 1;
        IF NOT EXISTS (SELECT 1 FROM dbo.USUARIOS2105 WHERE USUARIO_ID = @USUARIO_ID AND ACTIVO = 1)
            THROW 51101, 'El usuario no existe o esta inactivo.', 1;
        SET @AHORA = SYSUTCDATETIME();
        IF @ESTADO <> 'PUBLICADA' OR @AHORA < @INICIO OR @AHORA >= @FIN
            THROW 51102, 'La subasta no acepta ofertas en este momento.', 1;
        -- Criterio estricto de la rubrica: oferta > base, incluso la primera.
        IF @MONTO IS NULL OR @MONTO <= @BASE
            THROW 51103, 'La oferta debe superar el monto base.', 1;

        SELECT TOP (1) @ANTERIOR_MONTO = MONTO, @ANTERIOR_USUARIO_ID = USUARIO_ID
        FROM dbo.PUJAS2105
        WHERE SUBASTA_ID = @SUBASTA_ID
        ORDER BY MONTO DESC, PUJA_ID DESC;

        IF @ANTERIOR_MONTO IS NOT NULL AND
           (@MONTO <= @ANTERIOR_MONTO OR @MONTO < @ANTERIOR_MONTO * CAST(1.10 AS DECIMAL(3,2)))
            THROW 51104, 'La oferta debe superar la puja actual al menos un 10 por ciento.', 1;

        INSERT dbo.PUJAS2105 (SUBASTA_ID, USUARIO_ID, MONTO, CREADO_UTC)
        VALUES (@SUBASTA_ID, @USUARIO_ID, @MONTO, @AHORA);
        SET @PUJA_ID = CONVERT(BIGINT, SCOPE_IDENTITY());

        INSERT dbo.NOTIFICACIONES2105 (USUARIO_ID, SUBASTA_ID, TIPO)
        VALUES (@USUARIO_ID, @SUBASTA_ID, 'GANANDO');
        IF @ANTERIOR_USUARIO_ID IS NOT NULL AND @ANTERIOR_USUARIO_ID <> @USUARIO_ID
            INSERT dbo.NOTIFICACIONES2105 (USUARIO_ID, SUBASTA_ID, TIPO)
            VALUES (@ANTERIOR_USUARIO_ID, @SUBASTA_ID, 'SUPERADO');

        INSERT dbo.EVENTOS_SUBASTA2105 (SUBASTA_ID, TIPO, MONTO_PUBLICO)
        VALUES (@SUBASTA_ID, 'PUJA', @MONTO);
        COMMIT TRANSACTION;
        SELECT @PUJA_ID AS PUJA_ID, @MONTO AS MONTO_ACEPTADO;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

CREATE OR ALTER PROCEDURE dbo.CERRAR_SUBASTA2105
    @SUBASTA_ID BIGINT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @ESTADO VARCHAR(12), @FIN DATETIME2(3), @BASE DECIMAL(19,2),
            @GANADOR_ID BIGINT, @MEJOR_MONTO DECIMAL(19,2), @RESULTADO VARCHAR(8);
    BEGIN TRY
        BEGIN TRANSACTION;
        SELECT @ESTADO = ESTADO, @FIN = FIN_UTC, @BASE = PRECIO_BASE
        FROM dbo.SUBASTAS2105 WITH (UPDLOCK, HOLDLOCK)
        WHERE SUBASTA_ID = @SUBASTA_ID;

        IF @ESTADO IS NULL THROW 51200, 'La subasta no existe.', 1;
        IF @ESTADO <> 'PUBLICADA' THROW 51201, 'La subasta no esta publicada.', 1;
        IF SYSUTCDATETIME() < @FIN THROW 51202, 'La subasta no ha terminado.', 1;

        SELECT TOP (1) @GANADOR_ID = USUARIO_ID, @MEJOR_MONTO = MONTO
        FROM dbo.PUJAS2105 WHERE SUBASTA_ID = @SUBASTA_ID
        ORDER BY MONTO DESC, PUJA_ID DESC;
        SET @RESULTADO = CASE WHEN @MEJOR_MONTO > @BASE THEN 'VENDIDA' ELSE 'DESIERTA' END;
        UPDATE dbo.SUBASTAS2105
        SET ESTADO = 'CERRADA', RESULTADO = @RESULTADO, CERRADA_UTC = SYSUTCDATETIME()
        WHERE SUBASTA_ID = @SUBASTA_ID;

        IF @RESULTADO = 'VENDIDA'
            INSERT dbo.NOTIFICACIONES2105 (USUARIO_ID, SUBASTA_ID, TIPO)
            VALUES (@GANADOR_ID, @SUBASTA_ID, 'VENDIDA');
        INSERT dbo.EVENTOS_SUBASTA2105 (SUBASTA_ID, TIPO, MONTO_PUBLICO)
        VALUES (@SUBASTA_ID, 'CERRADA', @MEJOR_MONTO);
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

/*
  Operacion:
  - La API debe autenticar, calcular el ID de usuario desde la sesion y no admitir
    INSERT/UPDATE directos a PUJAS2105 por el rol de aplicacion.
  - Fotos y ficha tecnica se editan solo en borrador; el API comprueba pertenencia.
    La API comprueba asimismo formato y tamano del archivo antes de guardar la imagen.
  - Programar CERRAR_SUBASTA2105 al vencer FIN_UTC (SQL Server Agent o trabajador).
  - Un trabajador procesa EVENTOS_SUBASTA2105 por EVENTO_ID, emite a cada grupo de
    subasta por WebSocket/SignalR y marca PROCESADO_UTC; puede haber reintentos,
    por lo que el cliente deduplica por EVENTO_ID. Nunca difundir USUARIO_ID.
  - El catalogo consulta PUBLICADA con INICIO_UTC <= SYSUTCDATETIME() y
    FIN_UTC > SYSUTCDATETIME(); para subastas finalizadas filtra por hora y estado.
  - Las tres cuentas de prueba se crean con hash de contrasena hecho en el API;
    no insertar contrasenas en texto plano en esta base de datos.
*/
